%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/zhangh/Dropbox/publication/vtti/data/EventSelectionKeyTest.xlsx
%    Worksheet: Event Key
%
% Auto-generated by MATLAB on 04-Jun-2020 12:34:19

%% Setup the Import Options

function EventSelectionKeyTest =  readexcel()
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Event Key";
opts.DataRange = "A2:D1003";

% Specify column names and types
opts.VariableNames = ["FILE_ID", "EVENT_START_TIME", "EVENT_END_TIME", "EVENT_TYPE"];
opts.VariableTypes = ["double", "double", "double", "categorical"];
opts = setvaropts(opts, 4, "EmptyFieldRule", "auto");

% Import the data
EventSelectionKeyTest = readtable("/Users/zhangh/Dropbox/publication/vtti/data/EventSelectionKeyTest.xlsx", opts, "UseExcel", false);

EventSelectionKeyTest{1,4}



for i=1:height (EventSelectionKeyTest)
if(EventSelectionKeyTest{i,4}=="Baseline")
    
   EventSelectionKeyTest{i,5} = 0;
   
elseif (EventSelectionKeyTest{i,4}=="Crash")
    EventSelectionKeyTest{i,5} = 1;
  
else
    EventSelectionKeyTest{i,5} = 2;
end

end

 
EventSelectionKeyTest = removevars(EventSelectionKeyTest,{'EVENT_TYPE'});

EventSelectionKeyTest.Properties.VariableNames = {'ID' 'Start' 'End' 'Crash'}




%% Clear temporary variables
clear opts